Repository Hallym-HAH/SGSH, pull requests merged in 2025-04, with the labels that each got.

#6 #5/Feat 사용자 수집 목적 렌더링 페이지
  Web/app/contact/page.js
  Web/app/globals.css
  Web/app/page.js
  Web/package-lock.json
  Web/package.json
  Web/postcss.config.mjs
Labels: Feat, Style

#11 Feat: 홍보글 생성 기능 추가
  .gitignore
  Core/main.py
  Core/main_insta.py
  Core/requirements.txt
  Core/util/generator.py
  Core/util/generator_insta.py
  Core/util/information_extractor.py
  Core/util/keyword_extractor.py
  Core/util/main_Def.py
  Core/util/main_def_insta.py
  Core/util/style_extractor.py
Labels: Feat

#16 #9/Feat: 매출 계산기 기능 추가
  Web/app/manage/calc/page.js
Labels: Feat

#15 #12/Feat : 가게 디테일 페이지
  App/.env.example
  App/.flutter-plugins
  App/.flutter-plugins-dependencies
  App/.gitignore
  App/.metadata
Labels: Feat, Style

#19 #18/style: 가게디테일 페이지 디자인, 메인 화면 배너
  App/.flutter-plugins-dependencies
  App/assets/images/noimage.png
  App/lib/models/article.dart
  App/lib/models/business.dart
  App/lib/models/enroll_data.dart
  App/lib/pages/mainpage.dart
  App/lib/pages/storedetail.dart
  App/lib/services/slivertabbardelegate.dart
  App/pubspec.yaml
Labels: Style

#24 #23/Feat: DB에 저장된 가게 정보들만 핀
  App/.env.example
  App/.flutter-plugins-dependencies
  App/lib/pages/mappage.dart
  App/lib/services/marker_service.dart
Labels: Feat
